# Generated by Django 4.2.8 on 2023-12-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author_name', models.CharField(max_length=256)),
                ('language', models.CharField(choices=[('en', 'English'), ('sp', 'Spanish'), ('fr', 'French'), ('ge', 'German'), ('hi', 'Hindi')], default='en', max_length=2)),
            ],
        ),
    ]
