# Generated by Django 4.2.8 on 2023-12-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterUniqueTogether(
            name='books',
            unique_together={('title', 'author_name', 'language')},
        ),
    ]
